ServiceStation/ServiceStation/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiceStation.Controllers
{
    public class CarController : Controller
    {
        private ServiceStationDBEntities db = new ServiceStationDBEntities();

        //
        // GET: /Car/

        public ActionResult Index()
        {
            var cars = db.Cars.Include(c => c.Client);
            return View(cars.ToList());
        }

        //
        // GET: /Car/Details/5

        public ActionResult Details(int id = 0)
        {
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        public ActionResult Orders(int id)
        {
            List<Order> orders = db.Orders.Where(o => o.IdCar.Equals(id)).ToList();
            return View(orders);
        }

        //
        // GET: /Car/Create

        public ActionResult Create()
        {
            ViewBag.IdClient = new SelectList(db.Clients, "IdClient", "Name");
            return View();
        }

        //
        // POST: /Car/Create

        [HttpPost]
        public ActionResult Create(Car car)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdClient = new SelectList(db.Clients, "IdClient", "Name", car.IdClient);
            return View(car);
        }

        //
        // GET: /Car/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdClient = new SelectList(db.Clients, "IdClient", "Name", car.IdClient);
            return View(car);
        }

        //
        // POST: /Car/Edit/5

        [HttpPost]
        public ActionResult Edit(Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdClient = new SelectList(db.Clients, "IdClient", "Name", car.IdClient);
            return View(car);
        }

        //
        // GET: /Car/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        //
        // POST: /Car/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars.Find(id);
            List<Order> orders = db.Orders.ToList();
            int count = 0;
            for (int i = 0; i < orders.Count; i++)
            {
                if (orders[i].IdCar.Equals(id))
                {
                    count++;
                }
            }
            if (count == 0)
            {
                db.Cars.Remove(car);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ServiceStation/ServiceStation/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiceStation.Controllers
{
    public class ClientController : Controller
    {
        private ServiceStationDBEntities db = new ServiceStationDBEntities();

        //
        // GET: /Client/

        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }

        //
        // GET: /Client/Details/5

        public ActionResult Details(int id = 0)
        {
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        //
        // GET: /Client/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Client/Create

        [HttpPost]
        public ActionResult Create(Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        //
        // GET: /Client/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        public ActionResult Cars(int id)
        {
            return View(db.Cars.Where(c => c.IdClient.Equals(id)).ToList());
        }

        public ActionResult Orders(int id)
        {
            return View(db.Orders.Where(c => c.IdCar.Equals(id)).ToList());
        }

        public ActionResult Search()
        {
            return View();
        }
        //
        // POST: /Client/Edit/5

        [HttpPost]
        public ActionResult Edit(Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        //
        // GET: /Client/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        //
        // POST: /Client/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ServiceStation/ServiceStation/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiceStation.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Измените этот шаблон, чтобы быстро приступить к работе над приложением ASP.NET MVC.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Страница описания приложения.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Страница контактов.";

            return View();
        }

        public ActionResult Start()
        {
            //ViewBag.Message = "Стартовая страница.";

            return View();
        }
    }
}

ServiceStation/ServiceStation/Controllers/NewClientController.cs
using ServiceStation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiceStation.Controllers
{
    public class NewClientController : Controller
    {

        private ServiceStationDBEntities db = new ServiceStationDBEntities();

        //
        // GET: /NewClient/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(NewClient newClient)
        {
            List<Client> clients = db.Clients.Where(c => c.Name.Equals(newClient.Name) && c.Surname.Equals(newClient.Surname)).ToList();
            if (clients.Count != 0)
            {
                return View("Search", clients);
            }
            return View("NoClient");
        }

    }
}

ServiceStation/ServiceStation/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiceStation.Controllers
{
    public class OrderController : Controller
    {
        private ServiceStationDBEntities db = new ServiceStationDBEntities();

        //
        // GET: /Order/

        public ActionResult Index()
        {
            var orders = db.Orders.Include(o => o.Car);
            return View(orders.ToList());
        }

        //
        // GET: /Order/Details/5

        public ActionResult Details(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // GET: /Order/Create

        public ActionResult Create()
        {
            ViewBag.IdCar = new SelectList(db.Cars, "IdCar", "Make");
            return View();
        }

        //
        // POST: /Order/Create

        [HttpPost]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCar = new SelectList(db.Cars, "IdCar", "Make", order.IdCar);
            return View(order);
        }

        //
        // GET: /Order/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCar = new SelectList(db.Cars, "IdCar", "Make", order.IdCar);
            return View(order);
        }

        //
        // POST: /Order/Edit/5

        [HttpPost]
        public ActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCar = new SelectList(db.Cars, "IdCar", "Make", order.IdCar);
            return View(order);
        }

        //
        // GET: /Order/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // POST: /Order/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ServiceStation/ServiceStation/Views/Home/About.cshtml
@{
    ViewBag.Title = "О программе";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        В этой области можно указать дополнительные сведения.
    </p>

    <p>
        В этой области можно указать дополнительные сведения.
    </p>

    <p>
        В этой области можно указать дополнительные сведения.
    </p>
</article>

<aside>
    <h3>Заголовок боковой панели</h3>
    <p>
        В этой области можно указать дополнительные сведения.
    </p>
    <ul>
        <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
        <li>@Html.ActionLink("О программе", "About", "Home")</li>
        <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
    </ul>
</aside>

ServiceStation/ServiceStation/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакт";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Телефон</h3>
    </header>
    <p>
        <span class="label">Основной:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">Нерабочее время:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Адрес электронной почты</h3>
    </header>
    <p>
        <span class="label">Поддержка:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Маркетинг:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">Общие вопросы:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Адрес</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

ServiceStation/ServiceStation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home page";
}

<h1>
    ServiceStation
</h1>

ServiceStation/ServiceStation/Views/Home/Start.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
     @Styles.Render("~/Content/css")
     @Scripts.Render("~/bundles/modernizr")
    <style>
        .header_black {
            top: 0;
            right: 0;
            left: 0;
            height: 33px;
            border-bottom: 1px solid #000;
        }
        .wrapper {
            margin: 0 auto;
            width: 976px;
            position: relative;
            padding-top: 50px;
            padding-bottom: 7px;
            font-size: 13px;
            height: auto;
        }
        .content {
            border-radius: 10px;
            border: 1px solid rgb(14, 14, 14);
        }
        .header {
            position: absolute;
            left: 0;
            top: 0px;
            height: 90px;
        }
        .footer {
            padding: 15px 0 5px 0;
            width: 100%;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <div class="header_black"></div>
    <div class="wrapper">
        <div class="content">
             @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
               @RenderBody()
            </section>
        </div>
        <div class="header">
             <nav>
                <ul id="menu">
                   <li>@Html.ActionLink("Home page", "Index", "Home")</li>
                   <li>@Html.ActionLink("Check clients", "Index", "NewClient")</li>
                   <li>@Html.ActionLink("Clients", "Index", "Client")</li>
                   <li>@Html.ActionLink("Cars", "Index", "Car")</li>
                   <li>@Html.ActionLink("Orders", "Index", "Order")</li>        
                </ul>
            </nav>
        </div>
        <div class="footer">
            <p>&copy; @DateTime.Now.Year Created by Sergey Korolenko</p>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>